-- Ensure courses table has all required columns
ALTER TABLE courses ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS code TEXT NOT NULL DEFAULT '';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS instructor TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS credits INTEGER DEFAULT 3;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS semester TEXT DEFAULT 'Fall';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS year INTEGER DEFAULT EXTRACT(YEAR FROM CURRENT_DATE);
ALTER TABLE courses ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'STEM';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS is_ap BOOLEAN DEFAULT FALSE;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Ensure grades table has all required columns
ALTER TABLE grades ADD COLUMN IF NOT EXISTS client_id TEXT;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS course_id TEXT NOT NULL;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS title TEXT NOT NULL DEFAULT '';
ALTER TABLE grades ADD COLUMN IF NOT EXISTS type TEXT DEFAULT 'exam';
ALTER TABLE grades ADD COLUMN IF NOT EXISTS score NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS max_score NUMERIC NOT NULL DEFAULT 100;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS weight NUMERIC DEFAULT 10;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS date TEXT DEFAULT CURRENT_DATE;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_courses_client_id ON courses(client_id);
CREATE INDEX IF NOT EXISTS idx_grades_client_id ON grades(client_id);
CREATE INDEX IF NOT EXISTS idx_grades_course_id ON grades(course_id);
CREATE INDEX IF NOT EXISTS idx_courses_year ON courses(year);
CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category);
CREATE INDEX IF NOT EXISTS idx_courses_is_ap ON courses(is_ap);
